---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-client
  labels:
    group: browser-client
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      group: browser-client
      role: browser-application
  template:
    metadata:
      labels:
        group: browser-client
        role: browser-application
    spec:
      containers:
      - name: browser-client
        image: gcr.io/poutineer/browser-client:latest
        ports:
        - containerPort: 3000
        env:
        - name: SENTRY_URI
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: SENTRY_BROWSER_CLIENT_URI
        - name: REDIS_SIDEKIQ_DATABASE
          value: '0'
        - name: REDIS_CACHE_HOST
          value: redis-origin.default
        - name: WWW_ORIGIN
          value: "https://www.poutineer.com"
        - name: RESOURCE_ORIGIN
          value: "https://resources.poutineer.com"
