---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-api
  labels:
    service: resources-api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      service: resources-api
      role: http-api
      access: external
  template:
    metadata:
      labels:
        service: resources-api
        role: http-api
        access: external
    spec:
      containers:
      - name: resources-api
        image: gcr.io/experimental-works/blank-api-rails:latest
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: RAILS_MASTER_KEY
        - name: POSTGRES_HOST
          value: pgbouncer.default
        - name: POSTGRES_USERNAME
          value: application
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: POSTGRES_APPLICATION_PASSWORD
        - name: POSTGRES_DATABASE
          value: resources
        - name: SENTRY_URI
          valueFrom:
            secretKeyRef:
              name: runtime-secrets
              key: SENTRY_URI
        - name: REDIS_SIDEKIQ_HOST
          value: redis-origin.default
        - name: REDIS_SIDEKIQ_DATABASE
          value: "0"
        - name: REDIS_CACHE_HOST
          value: redis-origin.default
        - name: REDIS_CACHE_DATABASE
          value: "1"
        - name: REDIS_LOCK_HOST
          value: redis-origin.default
        - name: REDIS_LOCK_DATABASE
          value: "2"
        - name: REDIS_OBJECTS_HOST
          value: redis-origin.default
        - name: REDIS_OBJECTS_DATABASE
          value: "3"
