version: 2
shared:
  dockers:
    ruby: &ruby_docker
      image: "circleci/ruby:2.5.0"
      environment:
        BUNDLE_JOBS: 8
        BUNDLE_PATH: "./vendor/bundle"
        BUNDLE_RETRY: 2
        PGHOST: "127.0.0.1"
        PGUSER: "postgres"
        PORT: 3000
        RAILS_ENV: "test"
        WEB_CONCURRENCY: 2
        RAILS_MAX_THREADS: 2
        RACK_TIMEOUT_SERVICE_TIMEOUT: 25
        WWW_ORIGIN: "localhost"
        RESOURCES_ORIGIN: "http://localhost:3001"
        HOME_ORIGIN: "http://localhost:3001"
        RAILS_EMAIL_HOST: "localhost"
        RAILS_EMAIL_USER: "noreply"
        RAILS_HOST: "localhost"
        REDIS_REDLOCK_URL: "redis://localhost:6379/0"
        REDIS_REDLOCK_POOL_SIZE: 2
        REDIS_CACHE_URL: "redis://localhost:6379/1"
        REDIS_CACHE_POOL_SIZE: 2
        REDIS_OBJECTS_URL: "redis://localhost:6379/2"
        REDIS_OBJECTS_POOL_SIZE: 2
        REDIS_ACTION_CABLE_URL: "redis://localhost:6379/2"
        REDIS_ACTION_CABLE_POOL_SIZE: 2
        REDIS_SIDEKIQ_URL: "redis://localhost:6379/3"
        REDIS_SIDEKIQ_CLIENT_POOL_SIZE: 2
        REDIS_SIDEKIQ_SERVER_POOL_SIZE: 2
    postgres: &postgres_docker
      image: "circleci/postgres:10.4-alpine"
      environment:
        POSTGRES_DB: "blank_test"
        POSTGRES_USER: "blank"
    redis: &redis_docker
      image: "redis:3.2.12"
  caches:
    git_save: &git_save
      save_cache:
        key: "blank-v2-git-{{ .Branch }}-{{ .Revision }}"
        paths:
          - ".git/"
    git_restore: &git_restore
      restore_cache:
        keys:
          - "blank-v2-git-{{ .Branch }}-{{ .Revision }}"
          - "blank-v2-git-{{ .Branch }}-"
          - "blank-v2-git-"
    bundler_save: &bundler_save
      save_cache:
        key: "blank-v2-bundler-{{ .Branch }}-{{ checksum \"Gemfile.lock\" }}"
        paths:
          - "./vendor/bundle"
          - "/usr/local/bundle/config"
    bundler_restore: &bundler_restore
      restore_cache:
        keys:
          - "blank-v2-bundler-{{ .Branch }}-{{ checksum \"Gemfile.lock\" }}"
          - "blank-v2-bundler-{{ .Branch }}-"
          - "blank-v2-bundler-"
workflows:
  version: 2
  core:
    jobs:
      -
        server_dependencies_setup:
          context: "Rails Environment"
      -
        bundler_audit:
          context: "Rails Environment"
          requires:
            - "server_dependencies_setup"
      -
        brakeman:
          context: "Rails Environment"
          requires:
            - "server_dependencies_setup"
      -
        rubocop:
          context: "Rails Environment"
          requires:
            - "server_dependencies_setup"
      -
        rspec:
          context: "Rails Environment"
          requires:
            - "server_dependencies_setup"
jobs:
  server_dependencies_setup:
    docker:
      - *ruby_docker
    steps:
      - *git_restore
      - "checkout"
      - *git_save
      - *bundler_restore
      -
        run:
          name: "Install bundler dependencies"
          command: "bundle check || bundle install"
      - *bundler_save
  bundler_audit:
    docker:
      - *ruby_docker
    steps:
      - *git_restore
      - "checkout"
      - *bundler_restore
      -
        run:
          name: "Running bundler-audit"
          command: "bundle exec bundler-audit check --update"
  brakeman:
    docker:
      - *ruby_docker
    steps:
      - *git_restore
      - "checkout"
      - *bundler_restore
      -
        run:
          name: "Running brakeman"
          command: "bundle exec brakeman"
  rubocop:
    docker:
      - *ruby_docker
    steps:
      - *git_restore
      - "checkout"
      - *bundler_restore
      -
        run:
          name: "Running rubocop"
          command: "bundle exec rubocop --config .rubocop/config.yml --lint"
  rspec:
    docker:
      - *ruby_docker
      - *postgres_docker
      - *redis_docker
    steps:
      - *git_restore
      - "checkout"
      - *bundler_restore
      -
        run:
          name: "Database Healthcheck"
          command: "dockerize -wait tcp://localhost:5432 -timeout 1m"
      -
        run:
          name: "Adding postgresql to apt sources"
          command: "sudo su -c \"echo 'deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main' >> /etc/apt/sources.list.d/pgdg.list\""
      -
        run:
          name: "Fetching postgresql apt-key"
          command: "wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -"
      -
        run:
          name: "Installing postgres-client"
          command: "sudo apt-get update && sudo apt-get install postgresql-client-10"
      -
        run:
          name: "Load databsase schema"
          command: "bundle exec rake db:create --trace"
      -
        run:
          name: "Running RSpec"
          command: "bundle exec rspec --format RspecJunitFormatter --out ./tmp/rspec/rspec.xml --format progress $(circleci tests glob \"spec/**/*_spec.rb\" | circleci tests split --split-by=timings)"
      -
        store_test_results:
          path: "tmp/rspec/"
      -
        store_artifacts:
          path: "tmp/rspec/"
      -
        store_artifacts:
          path: "logs/"
