---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase
  labels:
    service: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      service: metabase
      role: browser-dashboard
  template:
    metadata:
      labels:
        service: metabase
        role: browser-dashboard
    spec:
      containers:
        -
          name: metabase
          image: "metabase/metabase:v0.30.1"
          imagePullPolicy: IfNotPresent
          env:
            -
              name: MB_JETTY_HOST
              value: "0.0.0.0"
            -
              name: MB_JETTY_PORT
              value: "3000"
            -
              name: MB_DB_TYPE
              value: h2
            -
              name: MB_PASSWORD_COMPLEXITY
              value: normal
            -
              name: MB_PASSWORD_LENGTH
              value: "6"
            -
              name: JAVA_TIMEZONE
              value: UTC
            -
              name: MB_EMOJI_IN_LOGS
              value: "true"
          ports:
            -
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
          resources:
            {}
---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  labels:
    service: metabase
    role: browser-dashboard
spec:
  type: ClusterIP
  ports:
    -
      name: metabase
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    service: metabase
    role: browser-dashboard
